CREATE TABLE IF NOT EXISTS post( 
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    nombre text NOT NULL CHECK (nombre <> ''), 
    descripcion TEXT NOT NULL CHECK (descripcion <> '') 
);